import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import { NavbarProvider } from "@/context/navbarContext";
import { HeaderNav } from "@/components/HeaderNav";
import { Footer } from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu} antialiased`}
      >
        <NavbarProvider>
          {/* NavBar */}
          <HeaderNav />
          <main>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </NavbarProvider>
      </body>
    </html>
  );
}
